
export const components: Record<string, string> = {
    "Window": "/documentation/window",
    "TextComponent": "/documentation/text",
    "ButtonComponent": "/documentation/button",
    "ImageComponent": "/documentation/image",
    "IconComponent": "/documentation/icon",
    "Instant": "/documentation/instant",
    "Column": "/documentation/instant",
    "Row": "/documentation/row",
    "Scaffold": "/documentation/scaffold",
    "CompactSpacer": "/documentation/compactspace",
    "NavigationInstant": "/documentation/navigationinstant",
    "VerticalScrollFrame": "/documentation/verticalscroll",
    "HorizontalScrollFrame": "/documentation/horizontalscroll",
    "IteratorComponent": "/documentation/iterator",
    "IteratorComponent<T>" : "/documentation/iterator",
    "Application": "/documentation/application",
    "FrameComponent": "/documentation/frame",
    "Dynamic": "/documentation/dynamic",
    "@Dynamic": "/documentation/dynamic",
    "Component": "/documentation/component",
    "@Component": "/documentation/component",
    "TransientComponent": "/documentation/transient",
    "@TransientComponent": "/documentation/transient",
    "PredicateComponent": "/documentation/predicate",
    "@PredicateComponent": "/documentation/predicate",
    "DistantComponent": "/documentation/distant",
    "@DistantComponent": "/documentation/distant",
    "StaticComponent": "/documentation/static",
    "@StaticComponent": "/documentation/static",
    "MacComponent": "/documentation/mac",
    "@MacComponent": "/documentation/mac",
    "WindowsComponent": "/documentation/windows",
    "@WindowsComponent": "/documentation/windows",
    "LinuxComponent": "/documentation/linux",
    "@LinuxComponent": "/documentation/linux",
    "PredicateResult": "/documentation/predicateresult",
}